/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adam' at '6/4/16 7:16 PM' with Gradle 2.9
 *
 * @author adam, @date 6/4/16 7:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
